---
- name: Create apache setting directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - "{{ apache_module_available_dir }}"
    - "{{ apache_module_enabled_dir }}"
    - "{{ apache_conf_available_dir }}"
    - "{{ apache_conf_enabled_dir }}"
    - "{{ apache_site_available_dir }}"
    - "{{ apache_site_enabled_dir }}"
    - "{{ apache_snippet_dir }}"
- name: Append include settings on base config
  ansible.builtin.lineinfile:
    path: "{{ apache_config_base_dir }}/apache2.conf"
    line: "{{ item }}"
  loop:
    - IncludeOptional mods-enabled/*.load
    - IncludeOptional mods-enabled/*.conf
    - IncludeOptional conf-enabled/*.conf
    - IncludeOptional sites-enabled/*.conf
- name: Update load module
  ansible.builtin.command:
    cmd: "{{ item.disabled | default(false) | ternary('a2dismod', 'a2enmod') }} {{ item.name }}"
    creates: "{{ item.disabled | default(false) | ternary(omit, apache_module_enabled_dir + '/' + item.name + '.load') }}"
    removes: "{{ item.disabled | default(false) | ternary(apache_module_enabled_dir + '/' + item.name + '.load', omit) }}"
  loop: "{{ apache_modules }}"
  loop_control:
    label: "{{ item.name }}"
- name: Create custom setting file
  ansible.builtin.template:
    src: custom.conf.j2
    dest: "{{ apache_conf_available_dir }}/z-custom.conf"
    mode: "0644"
  notify: restart apache
- name: Enable custom setting
  ansible.builtin.command:
    cmd: a2enconf z-custom
    creates: "{{ apache_conf_enabled_dir }}/z-custom.conf"
  notify: restart apache
- name: Copy snippet files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ apache_snippet_dir }}/{{ item | basename }}"
    mode: preserve
  loop: "{{ lookup('fileglob', 'files/*.conf', wantlist=True) }}"
  loop_control:
    label: "{{ item | basename }}"
- name: Create virtualhost setting files
  ansible.builtin.template:
    src: virtualhost.conf.j2
    dest: "{{ apache_site_available_dir }}/{{ vhost.key }}.conf"
    mode: "0644"
  vars:
    vhost_setting: "{{ vhost.value }}"
  loop: "{{ apache_vhosts | dict2items }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.key }}"
  notify: restart apache
- name: Change site config
  ansible.builtin.file:
    path: "{{ apache_site_enabled_dir }}/{{ vhost.key }}.conf"
    src: "{{ vhost.value.state | default(true) | ternary(apache_site_available_dir + '/' + vhost.key + '.conf', omit) }}"
    state: "{{ vhost.value.state | default(true) | ternary('link', 'absent') }}"
    mode: "0644"
  loop: "{{ apache_vhosts | dict2items }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.key }}"
  notify: restart apache
