---
apache_append_goaccess_repository: true

# common_users:
#   - name: vagrant
#     groups:
#       - wheel
apache_vhosts:
  000-default:
    default_server: true
    server_name: www.example.com
    server_alias:
      - example.com
    document_root: /var/www/html
  001-test-desable-virtualhost:
    server_name: www.example.org
    server_alias:
      - example.org
    document_root: /var/www/example.org
    state: false
  999-status:
    ip: 127.0.0.1
    port: 1080
    virtualhost_before_setting: |
      Listen 1080
      ExtendedStatus On
    extra_setting: |
      <Location /server-status>
        SetHandler server-status
        Require ip 127.0.0.1
      </Location>
