---
- name: Verify
  hosts: all
  gather_facts: false
  check_mode: true
  become: true
  tasks:
    ## リポジトリのテスト
    - name: Test goaccess repository
      block:
        - name: Check apt source setting
          ansible.builtin.stat:
            path: /etc/apt/sources.list.d/goaccess.sources
          register: goaccess_repo_result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - goaccess_repo_result.stat.exists
            fail_msg: "GoAccess repository source file not found"
            success_msg: "GoAccess repository source file exists"
    ## パッケージのテスト
    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['apache2'] is defined
          - ansible_facts.packages['goaccess'] is defined
        fail_msg: "Some required packages are not installed"
        success_msg: "All required packages are installed"
    ## ユーザーのテスト
    - name: Check user
      ansible.builtin.user:
        name: www-data
        system: true
      check_mode: true
      register: result
    - name: Assert user
      ansible.builtin.assert:
        that:
          - result is not changed
        fail_msg: "www-data user is not properly configured"
        success_msg: "www-data user is properly configured"
    ## グループのテスト
    - name: Check group
      ansible.builtin.group:
        name: www-data
        system: true
      check_mode: true
      register: result
    - name: Assert group
      ansible.builtin.assert:
        that:
          - result is not changed
        fail_msg: "www-data group is not properly configured"
        success_msg: "www-data group is properly configured"
    # ファイルのテスト
    - name: Test virtualhost enable
      block:
        - name: Check virtualhost setting
          ansible.builtin.stat:
            path: /etc/apache2/sites-available/000-default.conf
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - result.stat.exists
            fail_msg: "Apache virtual host file not found"
            success_msg: "Apache virtual host file exists"
        - name: Check virtualhost enabled
          ansible.builtin.stat:
            path: /etc/apache2/sites-enabled/000-default.conf
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - result.stat.exists
              - result.stat.islnk
              - result.stat.lnk_source == '/etc/apache2/sites-available/000-default.conf'
            fail_msg: "Apache virtual host symlink is not properly configured"
            success_msg: "Apache virtual host symlink is properly configured"
    - name: Test virtualhost disable
      block:
        - name: Check virtualhost setting
          ansible.builtin.stat:
            path: /etc/apache2/sites-available/001-test-desable-virtualhost.conf
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - result.stat.exists
            fail_msg: "Apache disabled virtual host file not found"
            success_msg: "Apache disabled virtual host file exists"
        - name: Check virtualhost disabled
          ansible.builtin.stat:
            path: /etc/apache2/sites-enabled/001-test-desable-virtualhost.conf
          register: result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - not result.stat.exists
            fail_msg: "Apache virtual host should not be enabled"
            success_msg: "Apache virtual host is properly disabled"
    ## サービスのテスト
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['apache2.service'] is defined
          - ansible_facts.services['apache2.service']['state'] == 'running'
          - ansible_facts.services['apache2.service']['status'] == 'enabled'
        fail_msg: "Apache2 service is not running or not enabled"
        success_msg: "Apache2 service is running and enabled"
    ## 待受ポートのテスト
    - name: Gather facts on listening ports
      community.general.listen_ports_facts:
        command: ss
    - name: Set assert variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | list }}"
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 80 in listen_tcp_posts
        fail_msg: "Apache2 is not listening on port 80"
        success_msg: "Apache2 is listening on port 80"
